import { useState } from "react"
import { generateQuery } from "../../../_template/src/Base/Helpers/generateQuery"
import { createAsyncGraphQLAction2 } from "../Core/createAsyncGraphQLAction2"
import { introspectionQuery } from "../Core/gqlClient2"
import { useAsync } from "./useAsyncThunkAction"
import { useEffect } from "react"
import { createQueryStrLazy } from "@hrbolek/uoisfrontend-gql-shared"

const introspectionAction = createAsyncGraphQLAction2(introspectionQuery)

export const useGQLType = (type) => {
    const { loading, error, data } = useAsync(introspectionAction)
    const [queryById, setById] = useState(null)
    const [ByIdAsyncAction, setByIdAsyncAction] = useState(null)
    
    useEffect(() => {
        if (data) {
            const introspection = data.data;
            const querydef = generateQuery(introspection, type)
            // console.log("useGQLType generated ById", querydef)
            if (querydef == null) {
                throw new Error("useGQLType: cannot generate query for type " + type)
            }
            // setById(() => createQueryStrLazy(querydef))
            setById(() => querydef)
            setByIdAsyncAction(() => createAsyncGraphQLAction2(querydef))
        }}, 
    [data, type])

    return { loading, error, 
        queryById, ByIdAsyncAction,
        // Page 
    }
}