import { useState } from "react"
import { generateEntityQuery, generateQuery, generateQueryVector, mutationQueries } from "../../../_template/src/Base/Helpers/generateQuery"
import { createAsyncGraphQLAction2 } from "../Core/createAsyncGraphQLAction2"
import { introspectionQuery } from "../Core/gqlClient2"
import { useAsync } from "./useAsyncThunkAction"
import { useEffect } from "react"
// import { createQueryStrLazy } from "@hrbolek/uoisfrontend-gql-shared"

const introspectionAction = createAsyncGraphQLAction2(introspectionQuery)

export const useGQLType = (type) => {
    const { loading, error, data } = useAsync(introspectionAction)
    const [queryById, setById] = useState(null)
    const [EntityAsyncAction, setEntityAsyncAction] = useState(null)
    const [ByIdAsyncAction, setByIdAsyncAction] = useState(null)
    const [PageAsyncAction, setPageAsyncAction] = useState(null)
    const [queryVector, setQueryVector] = useState(null)
    const [mutations, setMutations] = useState(null)
    
    useEffect(() => {
        if (data) {
            const introspection = data.data;
            const querydef = generateQuery(introspection, type)
            
            const entityquerydef = generateEntityQuery(introspection, type)
            const entityqueryAction = createAsyncGraphQLAction2(entityquerydef)
            const entityqueryActionId = ({ id }, gqlClient) => {
                const representations = [{ "__typename": type, id }]
                console.log("entityquerydef", representations, entityquerydef)
                return entityqueryAction({representations}, gqlClient)
            }
                
            const queryVector = generateQueryVector(introspection, type)
            setQueryVector(()=>queryVector)
            const mutations = mutationQueries(introspection, type)
            setMutations(()=>mutations)
            // console.log("useGQLType generated ById", querydef)
            // if (querydef == null) {
            //     throw new Error("useGQLType: cannot generate query for type " + type)
            // }
            // setById(() => createQueryStrLazy(querydef))
            setById(() => querydef)
            setByIdAsyncAction(() => querydef?createAsyncGraphQLAction2(querydef):entityqueryActionId)
            setPageAsyncAction(() => createAsyncGraphQLAction2(queryVector))
            setEntityAsyncAction(() => entityqueryActionId)
        }}, 
    [data, type])

    return { loading, error, 
        introspection: data?.data,
        queryById, 

        ByIdAsyncAction,
        EntityAsyncAction,
        
        queryVector,
        PageAsyncAction,

        mutations
        // Page 
    }
}

